version: '3.8'

services:
  postgres:
    image: postgres:16
    # volumes:
    #   - ./drizzle/migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "remix-spotify"
    ports:
      - "5432:5432"
